name: mwcdn
description: ...

version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_multipart: ^1.0.0
  sqflite_common_ffi: ^2.1.1+1
  sqflite_common: ^2.3.0
  crypto: ^3.0.2
  path: ^1.8.2
  collection: ^1.18.0
  intl: ^0.18.1
  sprintf: ^7.0.0
  vector_math: any
  json_schema: ^5.1.3
  meta: ^1.10.0
  merge_map_null_safety: ^2.0.0
  http: ^1.1.0
  markdown: ^7.1.1
  pdf: ^3.10.6
#  excel: ^4.0.0
  archive: ^3.4.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
