name: mwImageService
description: ...
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  sqflite_common_ffi: ^2.1.1+1
  sqflite_common: ^2.3.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
