name: mwcdn
description: ...

version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_multipart: ^1.0.0
  sqflite_common_ffi: ^2.1.1+1
  sqflite_common: ^2.3.0
  crypto: ^3.0.2
  path: ^1.8.2
  pdf: ^3.10.4
  collection: ^1.18.0
  intl: ^0.18.1
  sprintf: ^7.0.0
  vector_math: any

dev_dependencies:
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.15.0
