class Purpose {
  // Bank Debt
  static const String BANK_LOAN_DELAYED_DRAW_FUNDING = 'BKDF';
  static const String BANK_LOAN_FEES = 'BKFE';
  static const String BANK_LOAN_FUNDING_MEMO = 'BKFM';
  static const String BANK_LOAN_ACCRUED_INTEREST_PAYMENT = 'BKIP';
  static const String BANK_LOAN_PRINCIPAL_PAYDOWN = 'BKPP';

  // Card Settlement
  static const String CARD_BULK_CLEARING = 'CBLK';
  static const String CARD_PAYMENT_WITH_CASH_BACK = 'CDCB';
  static const String CASH_DISBURSEMENT_CASH_SETTLEMENT = 'CDCD';
  static const String CASH_DISBURSEMENT_WITH_SURCHARGING = 'CDCS';
  static const String CARD_DEFERRED_PAYMENT = 'CDDP';
  static const String ORIGINAL_CREDIT = 'CDOC';
  static const String QUASI_CASH = 'CDQC';
  static const String E_PURSE_TOP_UP = 'ETUP';
  static const String FEE_COLLECTION = 'FCOL';
  static const String MOBILE_TOP_UP = 'MTUP';

  // Cash Mgmt
  static const String ACCOUNT_MANAGEMENT = 'ACCT';
  static const String CASH_MANAGEMENT_TRANSFER = 'CASH';
  static const String COLLECTION_PAYMENT = 'COLL';
  static const String CASH_DISBURSEMENT_CASH_MANAGEMENT = 'CSDB';
  static const String DEPOSIT = 'DEPT';
  static const String INTRA_COMPANY_PAYMENT = 'INTC';
  static const String LIQUIDITY_MANAGEMENT = 'LIMA';
  static const String NETTING = 'NETT';

  // Collateral
  static const String BOND_FORWARD = 'BFWD';
  static const String CROSS_CURRENCY_IRS = 'CCIR';
  static const String CCP_CLEARED_INITIAL_MARGIN = 'CCPC';
  static const String CCP_CLEARED_VARIATION_MARGIN = 'CCPM';
  static const String CCP_CLEARED_INITIAL_MARGIN_SEGREGATED_CASH = 'CCSM';
  static const String CREDIT_DEFAULT_SWAP = 'CRDS';
  static const String CROSS_PRODUCT = 'CRPR';
  static const String CREDIT_SUPPORT = 'CRSP';
  static const String CREDIT_LINE = 'CRTL';
  static const String EQUITY_OPTION = 'EQPT';
  static const String EQUITY_SWAP = 'EQUS';
  static const String EXOTIC_OPTION = 'EXPT';
  static const String EXCHANGE_TRADED_DERIVATIVES = 'EXTD';
  static const String FIXED_INCOME = 'FIXI';
  static const String FORWARD_BROKER_OWNED_CASH_COLLATERAL = 'FWBC';
  static const String FORWARD_CLIENT_OWNED_CASH_COLLATERAL = 'FWCC';
  static const String FORWARD_BROKER_OWNED_CASH_COLLATERAL_SEGREGATED = 'FWSB';
  static const String FORWARD_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'FWSC';
  static const String DAILY_MARGIN_ON_LISTED_DERIVATIVES = 'MARG';
  static const String MBS_BROKER_OWNED_CASH_COLLATERAL = 'MBSB';
  static const String MBS_CLIENT_OWNED_CASH_COLLATERAL = 'MBSC';
  static const String FUTURES_INITIAL_MARGIN = 'MGCC';
  static const String
  FUTURES_INITIAL_MARGIN_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'MGSC';
  static const String CLIENT_OWNED_OCC_PLEDGED_COLLATERAL = 'OCCC';
  static const String OTC_OPTION_BROKER_OWNED_CASH_COLLATERAL = 'OPBC';
  static const String OTC_OPTION_CLIENT_OWNED_CASH_COLLATERAL = 'OPCC';
  static const String OTC_OPTION_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL =
      'OPSB';
  static const String OTC_OPTION_CLIENT_OWNED_CASH_SEGREGATED_CASH_COLLATERAL =
      'OPSC';
  static const String FX_OPTION = 'OPTN';
  static const String OTC_DERIVATIVES = 'OTCD';
  static const String REPURCHASE_AGREEMENT = 'REPO';
  static const String BILATERAL_REPO_BROKER_OWNED_COLLATERAL = 'RPBC';
  static const String REPO_CLIENT_OWNED_COLLATERAL = 'RPCC';
  static const String BILATERAL_REPO_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL =
      'RPSB';
  static const String BILATERAL_REPO_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL =
      'RPSC';
  static const String REVERSE_REPURCHASE_AGREEMENT = 'RVPO';
  static const String SECURITIES_BUY_SELL_SELL_BUY_BACK = 'SBSC';
  static const String SINGLE_CURRENCY_IRS_EXOTIC = 'SCIE';
  static const String SINGLE_CURRENCY_IRS = 'SCIR';
  static const String SECURITIES_CROSS_PRODUCTS = 'SCRP';
  static const String BROKER_OWNED_COLLATERAL_SHORT_SALE = 'SHBC';
  static const String CLIENT_OWNED_COLLATERAL_SHORT_SALE = 'SHCC';
  static const String SHORT_SELL = 'SHSL';
  static const String SECURITIES_LENDING_AND_BORROWING = 'SLEB';
  static const String SECURED_LOAN = 'SLOA';
  static const String SWAP_BROKER_OWNED_CASH_COLLATERAL = 'SWBC';
  static const String SWAP_CLIENT_OWNED_CASH_COLLATERAL = 'SWCC';
  static const String SWAPTION = 'SWPT';
  static const String SWAPS_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL = 'SWSB';
  static const String SWAPS_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'SWSC';
  static const String TO_BE_ANNOUNCED = 'TBAS';
  static const String TBA_BROKER_OWNED_CASH_COLLATERAL = 'TBBC';
  static const String TBA_CLIENT_OWNED_CASH_COLLATERAL = 'TBCC';
  static const String TREASURY_CROSS_PRODUCT = 'TRCP';

  // Commercial
  static const String AGRICULTURAL_TRANSFER = 'AGRT';
  static const String ACCOUNTS_RECEIVABLES_ENTRY = 'AREN';
  static const String BUSINESS_EXPENSES = 'BEXP';
  static const String BACK_OFFICE_CONVERSION_ENTRY = 'BOCE';
  static const String COMMERCIAL_PAYMENT = 'COMC';
  static const String COPYRIGHT = 'CPYR';
  static const String PURCHASE_SALE_OF_GOODS = 'GDDS';
  static const String PURCHASE_SALE_OF_GOODS_AND_SERVICES = 'GDSV';
  static const String PURCHASE_SALE_OF_GOODS_AND_SERVICES_WITH_CASH_BACK =
      'GSCB';
  static const String LICENSE_FEE = 'LICF';
  static const String MOBILE_P_B_PAYMENT = 'MP2B';
  static const String POINT_OF_PURCHASE_ENTRY = 'POPE';
  static const String ROYALTIES = 'ROYA';
  static const String PURCHASE_SALE_OF_SERVICES = 'SCVE';
  static const String SERVICE_CHARGES = 'SERV';
  static const String SUBSCRIPTION = 'SUBS';
  static const String SUPPLIER_PAYMENT = 'SUPP';
  static const String COMMERCIAL = 'TRAD';

  // Consumer
  static const String CHARITY_PAYMENT = 'CHAR';
  static const String CONSUMER_THIRD_PARTY_CONSOLIDATED_PAYMENT = 'COMT';
  static const String MOBILE_P_P_PAYMENT = 'MP2P';

  // E-Commerce
  static const String GUARANTEED_E_PAYMENT = 'ECPG';
  static const String E_PAYMENT_RETURN = 'ECPR';
  static const String NON_GUARANTEED_E_PAYMENT = 'ECPU';
  static const String EPAYMENT = 'EPAY';

  // Finance
  static const String CAR_LOAN_PRINCIPAL_REPAYMENT = 'CLPR';
  static const String COMPENSATION_PAYMENT = 'COMP';
  static const String DEBIT_COLLECTION_PAYMENT = 'DBTC';
  static const String GOVERNMENT_INSURANCE = 'GOVI';
  static const String HOUSING_LOAN_REPAYMENT = 'HLRP';
  static const String HOME_LOAN_SETTLEMENT = 'HLST';
  static const String INSURANCE_PREMIUM_CAR = 'INPC';
  static const String INSURANCE_PREMIUM_REFUND = 'INPR';
  static const String PAYMENT_OF_INSURANCE_CLAIM = 'INSC';
  static const String INSURANCE_PREMIUM = 'INSU';
  static const String INTEREST = 'INTE';
  static const String LABOR_INSURANCE = 'LBRI';
  static const String LIFE_INSURANCE = 'LIFI';
  static const String LOAN = 'LOAN';
  static const String LOAN_REPAYMENT = 'LOAR';
  static const String PAYMENT_BASED_ON_ENFORCEMENT_ORDER = 'PENO';
  static const String PROPERTY_INSURANCE = 'PPTI';
  static const String RENTAL_LEASE_GENERAL = 'RELG';
  static const String RECURRING_INSTALLMENT_PAYMENT = 'RINP';
  static const String TRUST_FUND = 'TRFD';

  // Foreign Exchange
  static const String FORWARD_FOREIGN_EXCHANGE = 'FORW';
  static const String FOREIGN_EXCHANGE_RELATED_NETTING = 'FXNT';

  // General
  static const String ADMINISTRATIVE_MANAGEMENT = 'ADMG';
  static const String ADVANCE_PAYMENT = 'ADVA';
  static const String BEARER_CHEQUE_DOMESTIC = 'BCDM';
  static const String BEARER_CHEQUE_FOREIGN = 'BCFG';
  static const String BUILDING_MAINTENANCE = 'BLDM';
  static const String BOND_FORWARD_NETTING = 'BNET';
  static const String CAPITAL_BUILDING = 'CBFF';
  static const String CAPITAL_BUILDING_RETIREMENT = 'CBFR';
  static const String CREDIT_CARD_PAYMENT = 'CCRD';
  static const String CREDIT_CARD_BILL = 'CDBL';
  static const String CANCELLATION_FEE = 'CFEE';
  static const String CARD_GENERATED_DIRECT_DEBIT = 'CGDD';
  static const String TRADE_SETTLEMENT_PAYMENT = 'CORT';
  static const String COSTS = 'COST';
  static const String CARPARK_CHARGES = 'CPKC';
  static const String DEBIT_CARD_PAYMENT = 'DCRD';
  static const String PRINTED_ORDER_DISBURSEMENT = 'DSMT';
  static const String DELIVER_AGAINST_PAYMENT = 'DVPM';
  static const String EDUCATION = 'EDUC';
  static const String FACTOR_UPDATE_RELATED_PAYMENT = 'FACT';
  static const String FINANCIAL_AID_IN_CASE_OF_NATURAL_DISASTER = 'FAND';
  static const String LATE_PAYMENT_OF_FEES_AND_CHARGES = 'FCPM';
  static const String PAYMENT_OF_FEES = 'FEES';
  static const String GOVERNMENT_PAYMENT = 'GOVT';
  static const String IRREVOCABLE_CREDIT_CARD_PAYMENT = 'ICCP';
  static const String IRREVOCABLE_DEBIT_CARD_PAYMENT = 'IDCP';
  static const String INSTALMENT_HIRE_PURCHASE_AGREEMENT = 'IHRP';
  static const String INSTALLMENT = 'INSM';
  static const String INVOICE_PAYMENT = 'IVPT';
  static const String MULTI_CURRENY_CHEQUE_DOMESTIC = 'MCDM';
  static const String MULTI_CURRENY_CHEQUE_FOREIGN = 'MCFG';
  static const String MULTIPLE_SERVICE_TYPES = 'MSVC';
  static const String NOT_OTHERWISE_SPECIFIED = 'NOWS';
  static const String ORDER_CHEQUE_DOMESTIC = 'OCDM';
  static const String ORDER_CHEQUE_FOREIGN = 'OCFG';
  static const String OPENING_FEE = 'OFEE';
  static const String OTHER = 'OTHR';
  static const String PREAUTHORIZED_DEBIT = 'PADD';
  static const String PAYMENT_TERMS = 'PTSP';
  static const String REPRESENTED_CHECK_ENTRY = 'RCKE';
  static const String RECEIPT_PAYMENT = 'RCPT';
  static const String REBATE = 'REBT';
  static const String REFUND = 'REFU';
  static const String RENT = 'RENT';
  static const String ACCOUNT_OVERDRAFT_REPAYMENT = 'REOD';
  static const String REIMBURSEMENT_OF_A_PREVIOUS_ERRONEOUS_TRANSACTION =
      'RIMB';
  static const String BILATERAL_REPO_INTERNET_NETTING = 'RPNT';
  static const String ROUND_ROBIN = 'RRBN';
  static const String REIMBURSEMENT_RECEIVED_CREDIT_TRANSFER = 'RRCT';
  static const String RELATED_REQUEST_TO_PAY = 'RRTP';
  static const String RECEIVE_AGAINST_PAYMENT = 'RVPM';
  static const String PAYMENT_SLIP_INSTRUCTION = 'SLPI';
  static const String SPLIT_PAYMENTS = 'SPLT';
  static const String STUDY = 'STDY';
  static const String TBA_PAIR_OFF_NETTING = 'TBAN';
  static const String TELECOMMUNICATIONS_BILL = 'TBIL';
  static const String TOWN_COUNCIL_SERVICE_CHARGES = 'TCSC';
  static const String TELEPHONE_INITIATED_TRANSACTION = 'TELI';
  static const String TMPG_CLAIM_PAYMENT = 'TMPG';
  static const String TRI_PARTY_REPO_INTEREST = 'TPRI';
  static const String TRI_PARTY_REPO_NETTING = 'TPRP';
  static const String TRUNCATED_PAYMENT_SLIP = 'TRNC';
  static const String TRAVELLER_CHEQUE = 'TRVC';
  static const String INTERNET_INITIATED_TRANSACTION = 'WEBI';

  // Instant Payments
  static const String INSTANT_PAYMENTS = 'IPAY';
  static const String INSTANT_PAYMENTS_CANCELLATION = 'IPCA';
  static const String INSTANT_PAYMENTS_FOR_DONATIONS = 'IPDO';
  static const String INSTANT_PAYMENTS_IN_E_COMMERCE_WITHOUT_ADDRESS_DATA =
      'IPEA';
  static const String INSTANT_PAYMENTS_IN_E_COMMERCE_WITH_ADDRESS_DATA = 'IPEC';
  static const String INSTANT_PAYMENTS_IN_E_COMMERCE = 'IPEW';
  static const String INSTANT_PAYMENTS_AT_POS = 'IPPS';
  static const String INSTANT_PAYMENTS_RETURN = 'IPRT';
  static const String INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITH_FA =
      'IPU2';
  static const String INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITHOUT_FA =
      'IPUW';

  // Investment
  static const String ANNUITY = 'ANNI';
  static const String CUSTODIAN_MANAGEMENT_FEE_INHOUSE = 'CAFI';
  static const String CAPITAL_FALLING_DUE_INHOUSE = 'CFDI';
  static const String COMMODITY_TRANSFER = 'CMDT';
  static const String DERIVATIVES = 'DERI';
  static const String DIVIDEND = 'DIVD';
  static const String FOREIGN_EXCHANGE = 'FREX';
  static const String HEDGING = 'HEDG';
  static const String INVESTMENT_AND_SECURITIES = 'INVS';
  static const String PRECIOUS_METAL = 'PRME';
  static const String SAVINGS = 'SAVG';
  static const String SECURITIES = 'SECU';
  static const String SECURITIES_PURCHASE_INHOUSE = 'SEPI';
  static const String TREASURY_PAYMENT = 'TREA';
  static const String UNIT_TRUST_PURCHASE = 'UNIT';

  // Listed Derivatives
  static const String FUTURES_NETTING_PAYMENT = 'FNET';
  static const String FUTURES = 'FUTR';

  // Medical
  static const String ANESTHESIA_SERVICES = 'ANTS';
  static const String CONVALESCENT_CARE_FACILITY = 'CVCF';
  static const String DURABLE_MEDICALE_EQUIPMENT = 'DMEQ';
  static const String DENTAL_SERVICES = 'DNTS';
  static const String HOME_HEALTH_CARE = 'HLTC';
  static const String HEALTH_INSURANCE = 'HLTI';
  static const String HOSPITAL_CARE = 'HSPC';
  static const String INTERMEDIATE_CARE_FACILITY = 'ICRF';
  static const String LONG_TERM_CARE_FACILITY = 'LTCF';
  static const String MEDICAL_AID_FUND_CONTRIBUTION = 'MAFC';
  static const String MEDICAL_AID_REFUND = 'MARF';
  static const String MEDICAL_SERVICES = 'MDCS';
  static const String VISION_CARE = 'VIEW';

  // OTC Derivatives
  static const String CREDIT_DEFAULT_EVENT_PAYMENT = 'CDEP';
  static const String SWAP_CONTRACT_FINAL_PAYMENT = 'SWFP';
  static const String SWAP_CONTRACT_PARTIAL_PAYMENT = 'SWPP';
  static const String SWAP_CONTRACT_RESET_PAYMENT = 'SWRS';
  static const String SWAP_CONTRACT_UPFRONT_PAYMENT = 'SWUF';

  // Salary & Benefits
  static const String ADVISORY_DONATION_COPYRIGHT_SERVICES = 'ADCS';
  static const String ACTIVE_EMPLOYMENT_POLICY = 'AEMP';
  static const String ALLOWANCE = 'ALLW';
  static const String ALIMONY_PAYMENT = 'ALMY';
  static const String BABY_BONUS_SCHEME = 'BBSC';
  static const String CHILD_BENEFIT = 'BECH';
  static const String UNEMPLOYMENT_DISABILITY_BENEFIT = 'BENE';
  static const String BONUS_PAYMENT = 'BONU';
  static const String CASH_COMPENSATION_HELPLESSNESS_DISABILITY = 'CCHD';
  static const String COMMISSION = 'COMM';
  static const String COMPANY_SOCIAL_LOAN_PAYMENT_TO_BANK = 'CSLP';
  static const String GUARANTEE_FUND_RIGHTS_PAYMENT = 'GFRP';
  static const String AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_A = 'GVEA';
  static const String AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_B = 'GVEB';
  static const String AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_C = 'GVEC';
  static const String AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_D = 'GVED';
  static const String GOVERMENT_WAR_LEGISLATION_TRANSFER = 'GWLT';
  static const String HOUSING_RELATED_CONTRIBUTION = 'HREC';
  static const String PAYROLL = 'PAYR';
  static const String PENSION_FUND_CONTRIBUTION = 'PEFC';
  static const String PENSION_PAYMENT = 'PENS';
  static const String PRICE_PAYMENT = 'PRCP';
  static const String REHABILITATION_SUPPORT = 'RHBS';
  static const String SALARY_PAYMENT = 'SALA';
  static const String SALARY_PENSION_SUM_PAYMENT = 'SPSP';
  static const String SOCIAL_SECURITY_BENEFIT = 'SSBE';

  // Securities Lending
  static const String LENDING_BUY_IN_NETTING = 'LBIN';
  static const String LENDING_CASH_COLLATERAL_FREE_MOVEMENT = 'LCOL';
  static const String LENDING_FEES = 'LFEE';
  static const String LENDING_EQUITY_MARKED_TO_MARKET_CASH_COLLATERAL = 'LMEQ';
  static const String LENDING_FIXED_INCOME_MARKED_TO_MARKET_CASH_COLLATERAL =
      'LMFI';
  static const String
  LENDING_UNSPECIFIED_TYPE_OF_MARKED_TO_MARKET_CASH_COLLATERAL = 'LMRK';
  static const String LENDING_REBATE_PAYMENTS = 'LREB';
  static const String LENDING_REVENUE_PAYMENTS = 'LREV';
  static const String LENDING_CLAIM_PAYMENT = 'LSFL';

  // Tax
  static const String ESTATE_TAX = 'ESTX';
  static const String FOREIGN_WORKER_LEVY = 'FWLV';
  static const String GOODS_SERVICES_TAX = 'GSTX';
  static const String HOUSING_TAX = 'HSTX';
  static const String INCOME_TAX = 'INTX';
  static const String NET_INCOME_TAX = 'NITX';
  static const String PROPERTY_TAX = 'PTXP';
  static const String ROAD_TAX = 'RDTX';
  static const String TAX_PAYMENT = 'TAXS';
  static const String VALUE_ADDED_TAX_PAYMENT = 'VATX';
  static const String WITH_HOLDING = 'WHLD';
  static const String TAX_REFUND = 'TAXR';

  // Trailer Fee
  static const String TRAILER_FEE_PAYMENT = 'B112';
  static const String TRAILER_FEE_REBATE = 'BR12';
  static const String NON_US_MUTUAL_FUND_TRAILER_FEE_PAYMENT = 'TLRF';
  static const String NON_US_MUTUAL_FUND_TRAILER_FEE_REBATE_PAYMENT = 'TLRR';

  // Transport
  static const String AIR = 'AIRB';
  static const String BUS = 'BUSB';
  static const String FERRY = 'FERB';
  static const String RAILWAY = 'RLWY';
  static const String ROAD_PRICING = 'TRPT';

  // Utilities
  static const String CABLE_TV_BILL = 'CBTV';
  static const String ELECTRICITY_BILL = 'ELEC';
  static const String ENERGIES = 'ENRG';
  static const String GAS_BILL = 'GASB';
  static const String NETWORK_CHARGE = 'NWCH';
  static const String NETWORK_COMMUNICATION = 'NWCM';
  static const String OTHER_TELECOM_RELATED_BILL = 'OTLC';
  static const String TELEPHONE_BILL = 'PHON';
  static const String UTILITIES = 'UBIL';
  static const String WATER_BILL = 'WTER';

  static const List<String> valid = [
    BANK_LOAN_DELAYED_DRAW_FUNDING,
    BANK_LOAN_FEES,
    BANK_LOAN_FUNDING_MEMO,
    BANK_LOAN_ACCRUED_INTEREST_PAYMENT,
    BANK_LOAN_PRINCIPAL_PAYDOWN,
    CARD_BULK_CLEARING,
    CARD_PAYMENT_WITH_CASH_BACK,
    CASH_DISBURSEMENT_CASH_SETTLEMENT,
    CASH_DISBURSEMENT_WITH_SURCHARGING,
    CARD_DEFERRED_PAYMENT,
    ORIGINAL_CREDIT,
    QUASI_CASH,
    E_PURSE_TOP_UP,
    FEE_COLLECTION,
    MOBILE_TOP_UP,
    ACCOUNT_MANAGEMENT,
    CASH_MANAGEMENT_TRANSFER,
    COLLECTION_PAYMENT,
    CASH_DISBURSEMENT_CASH_MANAGEMENT,
    DEPOSIT,
    INTRA_COMPANY_PAYMENT,
    LIQUIDITY_MANAGEMENT,
    NETTING,
    BOND_FORWARD,
    CROSS_CURRENCY_IRS,
    CCP_CLEARED_INITIAL_MARGIN,
    CCP_CLEARED_VARIATION_MARGIN,
    CCP_CLEARED_INITIAL_MARGIN_SEGREGATED_CASH,
    CREDIT_DEFAULT_SWAP,
    CROSS_PRODUCT,
    CREDIT_SUPPORT,
    CREDIT_LINE,
    EQUITY_OPTION,
    EQUITY_SWAP,
    EXOTIC_OPTION,
    EXCHANGE_TRADED_DERIVATIVES,
    FIXED_INCOME,
    FORWARD_BROKER_OWNED_CASH_COLLATERAL,
    FORWARD_CLIENT_OWNED_CASH_COLLATERAL,
    FORWARD_BROKER_OWNED_CASH_COLLATERAL_SEGREGATED,
    FORWARD_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL,
    DAILY_MARGIN_ON_LISTED_DERIVATIVES,
    MBS_BROKER_OWNED_CASH_COLLATERAL,
    MBS_CLIENT_OWNED_CASH_COLLATERAL,
    FUTURES_INITIAL_MARGIN,
    FUTURES_INITIAL_MARGIN_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL,
    CLIENT_OWNED_OCC_PLEDGED_COLLATERAL,
    OTC_OPTION_BROKER_OWNED_CASH_COLLATERAL,
    OTC_OPTION_CLIENT_OWNED_CASH_COLLATERAL,
    OTC_OPTION_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL,
    OTC_OPTION_CLIENT_OWNED_CASH_SEGREGATED_CASH_COLLATERAL,
    FX_OPTION,
    OTC_DERIVATIVES,
    REPURCHASE_AGREEMENT,
    BILATERAL_REPO_BROKER_OWNED_COLLATERAL,
    REPO_CLIENT_OWNED_COLLATERAL,
    BILATERAL_REPO_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL,
    BILATERAL_REPO_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL,
    REVERSE_REPURCHASE_AGREEMENT,
    SECURITIES_BUY_SELL_SELL_BUY_BACK,
    SINGLE_CURRENCY_IRS_EXOTIC,
    SINGLE_CURRENCY_IRS,
    SECURITIES_CROSS_PRODUCTS,
    BROKER_OWNED_COLLATERAL_SHORT_SALE,
    CLIENT_OWNED_COLLATERAL_SHORT_SALE,
    SHORT_SELL,
    SECURITIES_LENDING_AND_BORROWING,
    SECURED_LOAN,
    SWAP_BROKER_OWNED_CASH_COLLATERAL,
    SWAP_CLIENT_OWNED_CASH_COLLATERAL,
    SWAPTION,
    SWAPS_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL,
    SWAPS_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL,
    TO_BE_ANNOUNCED,
    TBA_BROKER_OWNED_CASH_COLLATERAL,
    TBA_CLIENT_OWNED_CASH_COLLATERAL,
    TREASURY_CROSS_PRODUCT,
    AGRICULTURAL_TRANSFER,
    ACCOUNTS_RECEIVABLES_ENTRY,
    BUSINESS_EXPENSES,
    BACK_OFFICE_CONVERSION_ENTRY,
    COMMERCIAL_PAYMENT,
    COPYRIGHT,
    PURCHASE_SALE_OF_GOODS,
    PURCHASE_SALE_OF_GOODS_AND_SERVICES,
    PURCHASE_SALE_OF_GOODS_AND_SERVICES_WITH_CASH_BACK,
    LICENSE_FEE,
    MOBILE_P_B_PAYMENT,
    POINT_OF_PURCHASE_ENTRY,
    ROYALTIES,
    PURCHASE_SALE_OF_SERVICES,
    SERVICE_CHARGES,
    SUBSCRIPTION,
    SUPPLIER_PAYMENT,
    COMMERCIAL,
    CHARITY_PAYMENT,
    CONSUMER_THIRD_PARTY_CONSOLIDATED_PAYMENT,
    MOBILE_P_P_PAYMENT,
    GUARANTEED_E_PAYMENT,
    E_PAYMENT_RETURN,
    NON_GUARANTEED_E_PAYMENT,
    EPAYMENT,
    CAR_LOAN_PRINCIPAL_REPAYMENT,
    COMPENSATION_PAYMENT,
    DEBIT_COLLECTION_PAYMENT,
    GOVERNMENT_INSURANCE,
    HOUSING_LOAN_REPAYMENT,
    HOME_LOAN_SETTLEMENT,
    INSURANCE_PREMIUM_CAR,
    INSURANCE_PREMIUM_REFUND,
    PAYMENT_OF_INSURANCE_CLAIM,
    INSURANCE_PREMIUM,
    INTEREST,
    LABOR_INSURANCE,
    LIFE_INSURANCE,
    LOAN,
    LOAN_REPAYMENT,
    PAYMENT_BASED_ON_ENFORCEMENT_ORDER,
    PROPERTY_INSURANCE,
    RENTAL_LEASE_GENERAL,
    RECURRING_INSTALLMENT_PAYMENT,
    TRUST_FUND,
    FORWARD_FOREIGN_EXCHANGE,
    FOREIGN_EXCHANGE_RELATED_NETTING,
    ADMINISTRATIVE_MANAGEMENT,
    ADVANCE_PAYMENT,
    BEARER_CHEQUE_DOMESTIC,
    BEARER_CHEQUE_FOREIGN,
    BUILDING_MAINTENANCE,
    BOND_FORWARD_NETTING,
    CAPITAL_BUILDING,
    CAPITAL_BUILDING_RETIREMENT,
    CREDIT_CARD_PAYMENT,
    CREDIT_CARD_BILL,
    CANCELLATION_FEE,
    CARD_GENERATED_DIRECT_DEBIT,
    TRADE_SETTLEMENT_PAYMENT,
    COSTS,
    CARPARK_CHARGES,
    DEBIT_CARD_PAYMENT,
    PRINTED_ORDER_DISBURSEMENT,
    DELIVER_AGAINST_PAYMENT,
    EDUCATION,
    FACTOR_UPDATE_RELATED_PAYMENT,
    FINANCIAL_AID_IN_CASE_OF_NATURAL_DISASTER,
    LATE_PAYMENT_OF_FEES_AND_CHARGES,
    PAYMENT_OF_FEES,
    GOVERNMENT_PAYMENT,
    IRREVOCABLE_CREDIT_CARD_PAYMENT,
    IRREVOCABLE_DEBIT_CARD_PAYMENT,
    INSTALMENT_HIRE_PURCHASE_AGREEMENT,
    INSTALLMENT,
    INVOICE_PAYMENT,
    MULTI_CURRENY_CHEQUE_DOMESTIC,
    MULTI_CURRENY_CHEQUE_FOREIGN,
    MULTIPLE_SERVICE_TYPES,
    NOT_OTHERWISE_SPECIFIED,
    ORDER_CHEQUE_DOMESTIC,
    ORDER_CHEQUE_FOREIGN,
    OPENING_FEE,
    OTHER,
    PREAUTHORIZED_DEBIT,
    PAYMENT_TERMS,
    REPRESENTED_CHECK_ENTRY,
    RECEIPT_PAYMENT,
    REBATE,
    REFUND,
    RENT,
    ACCOUNT_OVERDRAFT_REPAYMENT,
    REIMBURSEMENT_OF_A_PREVIOUS_ERRONEOUS_TRANSACTION,
    BILATERAL_REPO_INTERNET_NETTING,
    ROUND_ROBIN,
    REIMBURSEMENT_RECEIVED_CREDIT_TRANSFER,
    RELATED_REQUEST_TO_PAY,
    RECEIVE_AGAINST_PAYMENT,
    PAYMENT_SLIP_INSTRUCTION,
    SPLIT_PAYMENTS,
    STUDY,
    TBA_PAIR_OFF_NETTING,
    TELECOMMUNICATIONS_BILL,
    TOWN_COUNCIL_SERVICE_CHARGES,
    TELEPHONE_INITIATED_TRANSACTION,
    TMPG_CLAIM_PAYMENT,
    TRI_PARTY_REPO_INTEREST,
    TRI_PARTY_REPO_NETTING,
    TRUNCATED_PAYMENT_SLIP,
    TRAVELLER_CHEQUE,
    INTERNET_INITIATED_TRANSACTION,
    INSTANT_PAYMENTS,
    INSTANT_PAYMENTS_CANCELLATION,
    INSTANT_PAYMENTS_FOR_DONATIONS,
    INSTANT_PAYMENTS_IN_E_COMMERCE_WITHOUT_ADDRESS_DATA,
    INSTANT_PAYMENTS_IN_E_COMMERCE_WITH_ADDRESS_DATA,
    INSTANT_PAYMENTS_IN_E_COMMERCE,
    INSTANT_PAYMENTS_AT_POS,
    INSTANT_PAYMENTS_RETURN,
    INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITH_FA,
    INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITHOUT_FA,
    ANNUITY,
    CUSTODIAN_MANAGEMENT_FEE_INHOUSE,
    CAPITAL_FALLING_DUE_INHOUSE,
    COMMODITY_TRANSFER,
    DERIVATIVES,
    DIVIDEND,
    FOREIGN_EXCHANGE,
    HEDGING,
    INVESTMENT_AND_SECURITIES,
    PRECIOUS_METAL,
    SAVINGS,
    SECURITIES,
    SECURITIES_PURCHASE_INHOUSE,
    TREASURY_PAYMENT,
    UNIT_TRUST_PURCHASE,
    FUTURES_NETTING_PAYMENT,
    FUTURES,
    ANESTHESIA_SERVICES,
    CONVALESCENT_CARE_FACILITY,
    DURABLE_MEDICALE_EQUIPMENT,
    DENTAL_SERVICES,
    HOME_HEALTH_CARE,
    HEALTH_INSURANCE,
    HOSPITAL_CARE,
    INTERMEDIATE_CARE_FACILITY,
    LONG_TERM_CARE_FACILITY,
    MEDICAL_AID_FUND_CONTRIBUTION,
    MEDICAL_AID_REFUND,
    MEDICAL_SERVICES,
    VISION_CARE,
    CREDIT_DEFAULT_EVENT_PAYMENT,
    SWAP_CONTRACT_FINAL_PAYMENT,
    SWAP_CONTRACT_PARTIAL_PAYMENT,
    SWAP_CONTRACT_RESET_PAYMENT,
    SWAP_CONTRACT_UPFRONT_PAYMENT,
    ADVISORY_DONATION_COPYRIGHT_SERVICES,
    ACTIVE_EMPLOYMENT_POLICY,
    ALLOWANCE,
    ALIMONY_PAYMENT,
    BABY_BONUS_SCHEME,
    CHILD_BENEFIT,
    UNEMPLOYMENT_DISABILITY_BENEFIT,
    BONUS_PAYMENT,
    CASH_COMPENSATION_HELPLESSNESS_DISABILITY,
    COMMISSION,
    COMPANY_SOCIAL_LOAN_PAYMENT_TO_BANK,
    GUARANTEE_FUND_RIGHTS_PAYMENT,
    AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_A,
    AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_B,
    AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_C,
    AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_D,
    GOVERMENT_WAR_LEGISLATION_TRANSFER,
    HOUSING_RELATED_CONTRIBUTION,
    PAYROLL,
    PENSION_FUND_CONTRIBUTION,
    PENSION_PAYMENT,
    PRICE_PAYMENT,
    REHABILITATION_SUPPORT,
    SALARY_PAYMENT,
    SALARY_PENSION_SUM_PAYMENT,
    SOCIAL_SECURITY_BENEFIT,
    LENDING_BUY_IN_NETTING,
    LENDING_CASH_COLLATERAL_FREE_MOVEMENT,
    LENDING_FEES,
    LENDING_EQUITY_MARKED_TO_MARKET_CASH_COLLATERAL,
    LENDING_FIXED_INCOME_MARKED_TO_MARKET_CASH_COLLATERAL,
    LENDING_UNSPECIFIED_TYPE_OF_MARKED_TO_MARKET_CASH_COLLATERAL,
    LENDING_REBATE_PAYMENTS,
    LENDING_REVENUE_PAYMENTS,
    LENDING_CLAIM_PAYMENT,
    ESTATE_TAX,
    FOREIGN_WORKER_LEVY,
    GOODS_SERVICES_TAX,
    HOUSING_TAX,
    INCOME_TAX,
    NET_INCOME_TAX,
    PROPERTY_TAX,
    ROAD_TAX,
    TAX_PAYMENT,
    VALUE_ADDED_TAX_PAYMENT,
    WITH_HOLDING,
    TAX_REFUND,
    TRAILER_FEE_PAYMENT,
    TRAILER_FEE_REBATE,
    NON_US_MUTUAL_FUND_TRAILER_FEE_PAYMENT,
    NON_US_MUTUAL_FUND_TRAILER_FEE_REBATE_PAYMENT,
    AIR,
    BUS,
    FERRY,
    RAILWAY,
    ROAD_PRICING,
    CABLE_TV_BILL,
    ELECTRICITY_BILL,
    ENERGIES,
    GAS_BILL,
    NETWORK_CHARGE,
    NETWORK_COMMUNICATION,
    OTHER_TELECOM_RELATED_BILL,
    TELEPHONE_BILL,
    UTILITIES,
    WATER_BILL,
  ];
}