### create a resource
POST {{host}}/api/bucket/77/resource
Authorization: rootKey
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Type: application/json

{
}

--WebAppBoundary
Content-Disposition: form-data; filename="ffff23.jpg"
Content-Type: image/jpeg

< ./files/ffff23.jpg
--WebAppBoundary--

> {%
client.test('test', function () {
    client.assert(response.status === 200);
    client.global.set("resource_id1", response.body.id);
    client.global.set("resource_path", response.body.path);
    client.global.set("resource_filename", response.body.filename);
    client.global.set("resource_url", response.body.path + '/' + response.body.filename);
}); %}




### Show resource meta
GET {{host}}/api/bucket/77/resource/{{resource_id1}}
Authorization: rootKey

> scripts/assert200AndJson.js



### Show resource
GET {{host}}/{{resource_url}}

> scripts/assert200AndJpg.js

### Show resource
GET {{host}}/{{resource_path}}/{{resource_filename}}

> scripts/assert200AndJpg.js



### Show thumbnail
GET {{host}}/{{resource_path}}/thumb1-{{resource_filename}}

> scripts/assert200AndJpg.js



### flush
POST {{host}}/api/bucket/77/resource/{{resource_id1}}/flush
Authorization: rootKey



### Delete resource
DELETE {{host}}/api/bucket/77/resource/{{resource_id1}}
Authorization: rootKey